version: 2.1

executors:
  go:
    resource_class: medium
    docker:
      - image: cimg/go:1.25

  node:
    resource_class: medium
    docker:
      - image: cimg/node:current

jobs:
  build:
    executor: go
    steps:
      - checkout
      - run: task install
      - run: task build
      - run: task test
      - persist_to_workspace:
          root: .
          paths:
            - public

  deployment:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run deploy

workflows:
  version: 2

  pipeline:
    jobs:
      - build
      - deployment:
          context: Firebase
          requires:
            - build
          filters:
            branches:
              only: master
