defaults: &defaults
  working_directory: ~

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: felicianotech/docker-hugo:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v
      #- run:
      #    name: "Test Website"
      #    command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - persist_to_workspace:
          root: .
          paths:
            - public
            - firebase.json
            - .firebaserc
  deployment:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: .
      - restore_cache: # special step to restore the dependency cache 
          key: dependency-cache-firebase-tools
      - run:
          name: npm install firebase-tools
          command: npm install firebase-tools
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-firebase-tools
          paths:
            - ./node_modules
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token="$FIREBASE_DEPLOY_TOKEN"

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deployment:
          requires:
            - build